### ISSUE TITLE
Missing information in technical guide

### ISSUE THREAD

**Issue by mofa** [google-marketing-solutions/topic-mine#10]
In the technical guide, it seems there is missing information specifically on the Google sheets (refer to screenshot). can you pls advise?

<img width="645" alt="deployment below" src="https://github.com/google-marketing-solutions/topic-mine/assets/3746995/4ae16de3-206d-42ef-9d4e-1cfa36066894">

**Comment by JuanGriggio** [comment]
Thanks for pointing it out, fixed docs!
